package com.example.tablecreatepojo.dao;

import com.example.tablecreatepojo.entity.TFunction;
import java.util.List;

public interface TFunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int insert(TFunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    TFunction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    List<TFunction> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TFunction record);
}