package com.example.tablecreatepojo.dao;

import com.example.tablecreatepojo.entity.TFunctionRole;
import java.util.List;

public interface TFunctionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function_role
     *
     * @mbg.generated
     */
    int insert(TFunctionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_function_role
     *
     * @mbg.generated
     */
    List<TFunctionRole> selectAll();
}